os: linux
dist: bionic
language: scala
jdk:
  - openjdk8
before_install:
  - curl -sL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  - echo "deb https://packages.nginx.org/unit/ubuntu/ bionic unit" | sudo tee -a /etc/apt/sources.list.d/unit.list
  - echo "deb-src https://packages.nginx.org/unit/ubuntu/ bionic unit" | sudo tee -a /etc/apt/sources.list.d/unit.list  
  - sudo apt-get update
  - sudo apt-get install -y libuv1-dev unit-dev
script:
  - sbt scalafmtCheckAll exampleJS/fastOptJS exampleNative/nativeLink test
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.sbt
